### PR TITLE
Update JetBrains SDK to 2021.1

### LINKED ISSUE #76: Support Rider 2021.1 version

### PR DESCRIPTION
**Pull request by m7clarke**
- Version bump to 1.2.8.31
- Update Wave version to 211
- Update JetBrains.ReSharper.SDK version to 2021.1.0
- Update JetBrains.ReSharper.SDK.Tests version to 2021.1.0
- Update JetBrains.Rider.SDK version to 2021.1.0
- Update JetBrains.Rider.SDK.Tests version to 2021.1.0

Resolves #76

### CODE REVIEW

**Review by ristogod — APPROVED** [review]
Looks good. Let's roll.

**Comment by inyutin-maxim** [comment]
JetBrains present Workaround to fix problem for failed unit testing after Update SDK to 2021.1 version

https://youtrack.jetbrains.com/issue/RSRP-483974#focus=Comments-27-4830189.0-0

**Comment by ristogod** [comment]
anyone able to install this extension yet?

**Comment by tresoldigiorgio** [comment]
no.... :-(

**Pull request merged**
